// Declare list of products
const Data = [
    {
        id : 1,
        name : "Lite Racer Adapt 4",
        img: { "src": "Public/Products/Adidas/Lite Racer Adapt 4" },
        brand : "Adidas",
        amt : "80",
        category: "Running",
    },
    {
        id : 2,
        name : "Crayola",
        img : { "src": "Public/Products/Adidas/Crayola" },
        brand : "Adidas",
        amt : "90",
        category: "Basketball",
    },
    {
        id : 3,
        name : "Jordan 1",
        img : { "src": "Public/Products/Jordan/Jordan 1" },
        brand : "Jordan",
        amt : "120",
        category: "Basketball",
    },
    {
        id : 4,
        name : "Jordan 4",
        img : { "src": "Public/Products/Jordan/Jordan 4" },
        brand : "Jordan",
        amt : "150",
        category: "Basketball",
    },
    {
        id : 5,
        name : "Jordan 1 Retro",
        img : { "src": "Public/Products/Jordan/Jordan 1 Retro" },
        brand : "Jordan",
        amt : "125",
        category: "Basketball",
    },
    {
        id : 6,
        name : "Jordan 12 Retro",
        img : { "src": "Public/Products/Jordan/Jordan 12 Retro" },
        brand : "Jordan",
        amt : "170",
        category: "Basketball",
    },
    {
        id : 7,
        name : "Nike Ck Racer",
        img : { "src": "Public/Products/Nike/Nike Ck Racer" },
        brand : "Nike",
        amt : "60",
        category: "Running",
    },
    {
        id : 8,
        name : "Nike Kobe 6",
        img : { "src": "Public/Products/Nike/Nike Kobe 6" },
        brand : "Nike",
        amt : "250",
        category: "Basketball",
    },
    {
        id : 9,
        name : "Nike Viale GS",
        img : { "src": "Public/Products/Nike/Nike Viale GS" } ,
        brand : "Nike",
        amt : "75",
        category: "Fitness",
    },
    {
        id : 10,
        name : "Puma Axelion",
        img : { "src": "Public/Products/Puma/Puma Axelion" },
        brand : "Puma",
        amt : "50",
        category: "Fitness",
    },
    {
        id : 11,
        name : "Puma Fusion Grip",
        img : { "src": "Public/Products/Puma/Puma Fusion Grip" },
        brand : "Puma",
        amt : "70",
        category: "Golf",
    },
    {
        id : 12,
        name : "Skechers GOrun",
        img : { "src": "Public/Products/Puma/Puma Fusion Grip" } ,
        brand : "Skechers",
        amt : "50",
        category: "Running",
    },
    {
        id : 13,
        name : "Skechers Summits Training",
        img : { "src": "Public/Products/Skechers/Skechers Summits Training" } ,
        brand : "Skechers",
        amt : "70",
        category: "Fitness",
    },
    {
        id : 14,
        name : "Skechers Edgeride",
        img : { "src": "Public/Products/Skechers/Skechers Edgeride" },
        brand : "Skechers",
        amt : "80",
        category: "Running",
    },
    {
        id : 15,
        name : "UA Surge 4",
        img : { "src": "Public/Products/Under Armour/UA Surge 4" },
        brand : "Under Armour",
        amt : "80",
        category: "Running",
    },
    {
        id : 16,
        name : "UA GS Curry",
        img : { "src": "Public/Products/Under Rmour/UA GS Curry" },
        brand : "Under Armour",
        amt : "250",
        category: "Basketball",
    },
    {
        id : 17,
        name : "UA HAVOC 3",
        img :  { "src": "Public/Products/Under Rmour/UA HAVOC 3" },
        brand : "Under Armour",
        amt : "180",
        category: "Basketball",
    },
    {
        id : 18,
        name : "UA Charged 10",
        img :  { "src": "Public/Products/Under Rmour/UA Charger 10" },
        brand : "Under Armour",
        amt : "90",
        category: "Running",
    },    
];

// Declare variables
const productsContainer = document.querySelector(".products");
const categoyList = document.querySelector(".category-list");

