// Declare list of products
const Data = [
    {
        id : 1,
        name : "Crayola",
        img: { "src": "Public/Products/Adidas/Crayola" },
        brand : "Adidas",
        amt : "100",
        category: "Basketball",
        isNew : false,
    },
    {
        id : 2,
        name : "Lite Racer Adapt 4",
        img : { "src": "Public/Products/Adidas/Lite Racer Adapt 4" },
        brand : "Adidas",
        amt : "90",
        category: "Running",
        isNew : false,
    },
    {
        id : 3,
        name : "Yeezy Boost 350",
        img : { "src": "Public/Products/Adidas/Yeezy Boost 350" },
        brand : "Adidas",
        amt : "230",
        category: "Fitness",
        isNew : true,
    },
    {
        id : 4,
        name : "Yeezy Powerphase",
        img : { "src": "Public/Products/Adidas/Yeezy Powerphase" },
        brand : "Adidas",
        amt : "180",
        category: "Tennis",
        isNew : false,
    },
    {
        id : 5,
        name : "Jordan 1",
        img : { "src": "Public/Products/Jordan/Jordan 1" },
        brand : "Jordan",
        amt : "125",
        category: "Basketball",
        isNew : false,
    },
    {
        id : 6,
        name : "Jordan 4",
        img : { "src": "Public/Products/Jordan/Jordan 4" },
        brand : "Jordan",
        amt : "150",
        category: "Basketball",
        isNew : false,
    },
    {
        id : 7,
        name : "Jordan 1 Retro",
        img : { "src": "Public/Products/Jordan/Jordan 1 Retro" },
        brand : "Jordan",
        amt : "135",
        category: "Basketball",
        isNew : true,
    },
    {
        id : 8,
        name : "Jordan 11 Retro",
        img : { "src": "Public/Products/Jordan/Jordan 11 Retro" },
        brand : "Jordan",
        amt : "250",
        category: "Basketball",
        isNew : false,
    },
    {
        id : 9,
        name : "Nike Ck Racer",
        img : { "src": "Public/Products/Nike/Nike Ck Racer" },
        brand : "Nike",
        amt : "70",
        category: "Running",
        isNew : false,
    },
    {
        id : 10,
        name : "Nike Kobe 6",
        img : { "src": "Public/Products/Nike/Nike Kobe 6" },
        brand : "Nike",
        amt : "250",
        category: "Basketball",
        isNew : true,
    },
    {
        id : 11,
        name : "Nike Viale GS",
        img : { "src": "Public/Products/Nike/Nike Viale GS" } ,
        brand : "Nike",
        amt : "75",
        category: "Fitness",
        isNew : false,
    },
    {
        id : 12,
        name : "Puma Axelion",
        img : { "src": "Public/Products/Puma/Puma Axelion" },
        brand : "Puma",
        amt : "60",
        category: "Fitness",
        isNew : false,
    },
    {
        id : 13,
        name : "Puma Fusion Grip",
        img : { "src": "Public/Products/Puma/Puma Fusion Grip" },
        brand : "Puma",
        amt : "70",
        category: "Golf",
        isNew : false,
    },
    {
        id : 14,
        name : "Skechers GOrun",
        img : { "src": "Public/Products/Puma/Puma Fusion Grip" } ,
        brand : "Skechers",
        amt : "65",
        category: "Running",
        isNew : false,
    },
    {
        id : 15,
        name : "Skechers Summits Training",
        img : { "src": "Public/Products/Skechers/Skechers Summits Training" } ,
        brand : "Skechers",
        amt : "70",
        category: "Fitness",
        isNew : false,
    },
    {
        id : 16,
        name : "Skechers Edgeride",
        img : { "src": "Public/Products/Skechers/Skechers Edgeride" },
        brand : "Skechers",
        amt : "80",
        category: "Running",
        isNew : false,
    },
    {
        id : 17,
        name : "UA Surge 4",
        img : { "src": "Public/Products/Under Armour/UA Surge 4" },
        brand : "Under Armour",
        amt : "80",
        category: "Running",
        isNew : false,
    },
    {
        id : 18,
        name : "UA GS Curry",
        img : { "src": "Public/Products/Under Armour/UA GS Curry" },
        brand : "Under Armour",
        amt : "250",
        category: "Basketball",
        isNew : true,
    },
    {
        id : 19,
        name : "UA HAVOC 3",
        img :  { "src": "Public/Products/Under Armour/UA HAVOC 3" },
        brand : "Under Armour",
        amt : "180",
        category: "Basketball",
        isNew : false,
    },
    {
        id : 20,
        name : "UA Charged 10",
        img :  { "src": "Public/Products/Under Armour/UA Charger 10" },
        brand : "Under Armour",
        amt : "90",
        category: "Running",
        isNew : false,
    },    
];

// Declare variables
const productsContainer = document.querySelector(".products");
const categoyList = document.querySelector(".category-list");

// Function display shoes based on category
function displayProducts(products) {
    
}

// Function that will detect when a user makes a selection

