// Declare list of products
const Data = [
    {
        id : 1,
        name : "Lite Racer Adapt 4",
        img : "",
        brand : "Adidas",
        amt : "80",
        category: "Running",
    },
    {
        id : 2,
        name : "Crayola",
        img : " ",
        brand : "Adidas",
        amt : "90",
        category: "Basketball",
    },
    {
        id : 3,
        name : " ",
        img : " ",
        brand : " ",
        amt : " ",
        category: " ",
    },
    {
        id : 4,
        name : " ",
        img : " ",
        brand : " ",
        amt : " ",
        category: " ",
    },
    {
        id : 5,
        name : " ",
        img : " ",
        brand : " ",
        amt : " ",
        category: " ",
    },
    {
        id : 6,
        name : " ",
        img : " ",
        brand : " ",
        amt : " ",
        category: " ",
    },
    {
        id : 7,
        name : " ",
        img : " ",
        brand : " ",
        amt : " ",
        category: " ",
    },
    {
        id : 8,
        name : " ",
        img : " ",
        brand : " ",
        amt : " ",
        category: " ",
    },
    {
        id : 9,
        name : " ",
        img : " ",
        brand : " ",
        amt : " ",
        category: " ",
    },
    {
        id : 10,
        name : " ",
        img : " ",
        brand : " ",
        amt : " ",
        category: " ",
    },
    {
        id : 11,
        name : " ",
        img : " ",
        brand : " ",
        amt : " ",
        category: " ",
    },
    {
        id : 12,
        name : " ",
        img : " ",
        brand : " ",
        amt : " ",
        category: " ",
    },
    {
        id : 13,
        name : " ",
        img : " ",
        brand : " ",
        amt : " ",
        category: " ",
    },
    {
        id : 14,
        name : " ",
        img : " ",
        brand : " ",
        amt : " ",
        category: " ",
    },
    {
        id : 15,
        name : " ",
        img : " ",
        brand : " ",
        amt : " ",
        category: " ",
    },
    {
        id : 16,
        name : " ",
        img : " ",
        brand : " ",
        amt : " ",
        category: " ",
    },
    {
        id : 17,
        name : " ",
        img : " ",
        brand : " ",
        amt : " ",
        category: " ",
    },
    {
        id : 18,
        name : " ",
        img : " ",
        brand : " ",
        amt : " ",
        category: " ",
    },
    {
        id : 19,
        name : " ",
        img : " ",
        brand : " ",
        amt : " ",
        category: " ",
    },
    {
        id : 20,
        name : " ",
        img : " ",
        brand : " ",
        amt : " ",
        category: " ",
    },
];

// Declare variables


